// <auto-generated />
using System;
using EnterpriseCommerce.Infrastructure.Persistence;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace EnterpriseCommerce.Infrastructure.Migrations
{
    [DbContext(typeof(EnterpriseCommerceDbContext))]
    [Migration("20260827165849_AddPaymentMVP")]
    partial class AddPaymentMVP
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "8.0.2")
                .HasAnnotation("Relational:MaxIdentifierLength", 64);

            MySqlModelBuilderExtensions.AutoIncrementColumns(modelBuilder);

            modelBuilder.Entity("EnterpriseCommerce.Domain.Catalog.Product", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("char(36)");

                    b.Property<string>("Currency")
                        .IsRequired()
                        .HasMaxLength(3)
                        .HasColumnType("varchar(3)");

                    b.Property<bool>("IsActive")
                        .HasColumnType("tinyint(1)");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("varchar(255)");

                    b.Property<decimal>("Price")
                        .HasColumnType("decimal(18,2)");

                    b.Property<string>("Sku")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("varchar(100)");

                    b.Property<uint>("Version")
                        .IsConcurrencyToken()
                        .HasColumnType("int unsigned");

                    b.HasKey("Id");

                    b.HasIndex("Sku")
                        .IsUnique();

                    b.ToTable("Products", (string)null);
                });

            modelBuilder.Entity("EnterpriseCommerce.Domain.Inventory.InventoryItem", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("char(36)");

                    b.Property<int>("AvailableQuantity")
                        .HasColumnType("int");

                    b.Property<Guid>("ProductReference")
                        .HasColumnType("char(36)");

                    b.Property<int>("ReservedQuantity")
                        .HasColumnType("int");

                    b.Property<uint>("Version")
                        .IsConcurrencyToken()
                        .HasColumnType("int unsigned");

                    b.HasKey("Id");

                    b.ToTable("InventoryItems", (string)null);
                });

            modelBuilder.Entity("EnterpriseCommerce.Domain.Orders.Order", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("char(36)");

                    b.Property<string>("Currency")
                        .IsRequired()
                        .HasMaxLength(3)
                        .HasColumnType("varchar(3)");

                    b.Property<Guid>("CustomerId")
                        .HasColumnType("char(36)");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasColumnType("varchar(255)");

                    b.Property<DateTimeOffset?>("SubmittedAt")
                        .HasColumnType("datetime(6)");

                    b.Property<uint>("Version")
                        .IsConcurrencyToken()
                        .HasColumnType("int unsigned");

                    b.HasKey("Id");

                    b.HasIndex("Status", "SubmittedAt");

                    b.ToTable("Orders", (string)null);
                });

            modelBuilder.Entity("EnterpriseCommerce.Domain.Orders.OrderItem", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("char(36)");

                    b.Property<Guid>("OrderId")
                        .HasColumnType("char(36)");

                    b.Property<Guid>("ProductId")
                        .HasColumnType("char(36)");

                    b.Property<int>("Quantity")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("OrderId");

                    b.ToTable("OrderItems", (string)null);
                });

            modelBuilder.Entity("EnterpriseCommerce.Domain.Payments.PaymentAttempt", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("char(36)");

                    b.Property<DateTimeOffset?>("CompletedAt")
                        .HasColumnType("datetime(6)");

                    b.Property<DateTimeOffset>("CreatedAt")
                        .HasColumnType("datetime(6)");

                    b.Property<Guid>("IdempotencyKey")
                        .HasColumnType("char(36)");

                    b.Property<Guid>("OrderId")
                        .HasColumnType("char(36)");

                    b.Property<string>("Provider")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("varchar(50)");

                    b.Property<string>("ProviderTransactionId")
                        .HasMaxLength(100)
                        .HasColumnType("varchar(100)");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<uint>("Version")
                        .IsConcurrencyToken()
                        .HasColumnType("int unsigned");

                    b.HasKey("Id");

                    b.HasIndex("OrderId");

                    b.HasIndex("ProviderTransactionId");

                    b.HasIndex("OrderId", "IdempotencyKey")
                        .IsUnique();

                    b.HasIndex("Provider", "ProviderTransactionId")
                        .IsUnique();

                    b.ToTable("PaymentAttempts", (string)null);
                });

            modelBuilder.Entity("EnterpriseCommerce.Domain.Payments.PaymentWebhookReceipt", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("char(36)");

                    b.Property<Guid?>("PaymentAttemptId")
                        .HasColumnType("char(36)");

                    b.Property<string>("Provider")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("varchar(50)");

                    b.Property<string>("ProviderEventId")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("varchar(100)");

                    b.Property<DateTimeOffset>("ReceivedAt")
                        .HasColumnType("datetime(6)");

                    b.HasKey("Id");

                    b.HasIndex("Provider", "ProviderEventId")
                        .IsUnique();

                    b.ToTable("PaymentWebhookReceipts", (string)null);
                });

            modelBuilder.Entity("EnterpriseCommerce.Infrastructure.Persistence.Outbox.OutboxMessage", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("char(36)");

                    b.Property<string>("Content")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<string>("Error")
                        .HasColumnType("longtext");

                    b.Property<string>("EventType")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<DateTime>("OccurredOn")
                        .HasColumnType("datetime(6)");

                    b.Property<DateTime?>("ProcessedOn")
                        .HasColumnType("datetime(6)");

                    b.HasKey("Id");

                    b.ToTable("OutboxMessages");
                });

            modelBuilder.Entity("EnterpriseCommerce.Domain.Inventory.InventoryItem", b =>
                {
                    b.OwnsMany("EnterpriseCommerce.Domain.Inventory.InventoryReservation", "Reservations", b1 =>
                        {
                            b1.Property<Guid>("Id")
                                .HasColumnType("char(36)");

                            b1.Property<DateTimeOffset>("CreatedAt")
                                .HasColumnType("datetime(6)");

                            b1.Property<Guid>("InventoryItemId")
                                .HasColumnType("char(36)");

                            b1.Property<Guid>("OrderReference")
                                .HasColumnType("char(36)");

                            b1.Property<int>("Quantity")
                                .HasColumnType("int");

                            b1.HasKey("Id");

                            b1.HasIndex("InventoryItemId");

                            b1.ToTable("InventoryReservations", (string)null);

                            b1.WithOwner()
                                .HasForeignKey("InventoryItemId");
                        });

                    b.Navigation("Reservations");
                });

            modelBuilder.Entity("EnterpriseCommerce.Domain.Orders.OrderItem", b =>
                {
                    b.HasOne("EnterpriseCommerce.Domain.Orders.Order", null)
                        .WithMany("Items")
                        .HasForeignKey("OrderId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.OwnsOne("EnterpriseCommerce.Domain.Orders.ValueObjects.Money", "UnitPrice", b1 =>
                        {
                            b1.Property<Guid>("OrderItemId")
                                .HasColumnType("char(36)");

                            b1.Property<decimal>("Amount")
                                .HasPrecision(18, 4)
                                .HasColumnType("decimal(18,4)")
                                .HasColumnName("UnitPriceAmount");

                            b1.Property<string>("Currency")
                                .IsRequired()
                                .HasMaxLength(3)
                                .HasColumnType("varchar(3)")
                                .HasColumnName("UnitPriceCurrency");

                            b1.HasKey("OrderItemId");

                            b1.ToTable("OrderItems");

                            b1.WithOwner()
                                .HasForeignKey("OrderItemId");
                        });

                    b.Navigation("UnitPrice")
                        .IsRequired();
                });

            modelBuilder.Entity("EnterpriseCommerce.Domain.Payments.PaymentAttempt", b =>
                {
                    b.OwnsOne("EnterpriseCommerce.Domain.Orders.ValueObjects.Money", "Amount", b1 =>
                        {
                            b1.Property<Guid>("PaymentAttemptId")
                                .HasColumnType("char(36)");

                            b1.Property<decimal>("Amount")
                                .HasColumnType("decimal(18,2)")
                                .HasColumnName("Amount");

                            b1.Property<string>("Currency")
                                .IsRequired()
                                .HasMaxLength(3)
                                .HasColumnType("varchar(3)")
                                .HasColumnName("Currency");

                            b1.HasKey("PaymentAttemptId");

                            b1.ToTable("PaymentAttempts");

                            b1.WithOwner()
                                .HasForeignKey("PaymentAttemptId");
                        });

                    b.Navigation("Amount")
                        .IsRequired();
                });

            modelBuilder.Entity("EnterpriseCommerce.Domain.Orders.Order", b =>
                {
                    b.Navigation("Items");
                });
#pragma warning restore 612, 618
        }
    }
}
